### ISSUE TITLE
default window size is problematic

### ISSUE THREAD

**Issue by martey** [avelino/rdio-linux#10]
The [window resizing that occurs during the application's initialization](https://github.com/avelino/rdio-linux/blob/4fcb650618f867ad01adae94ba1a3821d0c2d594/rdio/player/rdio-player#L16) will only work properly with a minority of screen sizes.

The height of the window is hardcoded to 800 pixels. This could cause issues if used on a computer with a 1366x768 screen.

The width of the window is hardcoded to the screen width minus 100 pixels. This leads to weird issues on high-resolution screens (especially with the aforementioned 800px height) and with horizontal multi-monitor setups (the window spans across all monitors).

This issue is aggravated by #7.

**Comment by ghost** [comment]
the Rdio element resizes with the window now.
